# Generated by Django 5.2.12 on 2026-04-10 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('analamanga', 'Analamanga'), ('vakinankaratra', 'Vakinankaratra'), ('itasy', 'Itasy'), ('bongolava', 'Bongolava'), ('haute_matsiatra', 'Haute Matsiatra'), ('amoron_i_mania', "Amoron'i Mania"), ('vatovavy', 'Vatovavy'), ('fitovinany', 'Fitovinany'), ('ihorombe', 'Ihorombe'), ('atsimo_atsinanana', 'Atsimo-Atsinanana'), ('atsinanana', 'Atsinanana'), ('analanjirofo', 'Analanjirofo'), ('alaotra_mangoro', 'Alaotra-Mangoro'), ('boeny', 'Boeny'), ('sofia', 'Sofia'), ('betsiboka', 'Betsiboka'), ('melaky', 'Melaky'), ('atsimo_andrefana', 'Atsimo-Andrefana'), ('androy', 'Androy'), ('anosy', 'Anosy'), ('menabe', 'Menabe'), ('diana', 'Diana'), ('sava', 'SAVA')], max_length=50)),
                ('area_hectares', models.FloatField(help_text='Surface en hectares')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude_m', models.IntegerField(blank=True, help_text='Altitude en mètres', null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('rice', 'Riz'), ('cassava', 'Manioc'), ('maize', 'Maïs'), ('vanilla', 'Vanille'), ('cloves', 'Girofle'), ('coffee', 'Café'), ('lychee', 'Litchi'), ('other', 'Autre')], max_length=30)),
                ('variety', models.CharField(blank=True, help_text='Variété spécifique ex: FOFIFA 154', max_length=100)),
                ('soil_type', models.CharField(choices=[('laterite', 'Latérite'), ('alluvial', 'Alluvial'), ('volcanic', 'Volcanique'), ('sandy', 'Sableux'), ('clay', 'Argileux'), ('loam', 'Limon')], max_length=30)),
                ('planted_at', models.DateField()),
                ('expected_harvest', models.DateField()),
                ('actual_harvest', models.DateField(blank=True, null=True)),
                ('actual_yield_kg', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('growing', 'En croissance'), ('harvested', 'Récolté'), ('failed', 'Échec')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='crops.farm')),
            ],
            options={
                'ordering': ['-planted_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(blank=True, help_text='pH du sol (0-14)', null=True)),
                ('nitrogen_ppm', models.FloatField(blank=True, null=True)),
                ('phosphorus_ppm', models.FloatField(blank=True, null=True)),
                ('potassium_ppm', models.FloatField(blank=True, null=True)),
                ('organic_matter_percent', models.FloatField(blank=True, null=True)),
                ('moisture_percent', models.FloatField(blank=True, null=True)),
                ('sampled_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to='crops.farm')),
            ],
            options={
                'ordering': ['-sampled_at'],
            },
        ),
    ]
